### ISSUE TITLE
Error: command 'ruff.applyAutofix' already exists

### ISSUE THREAD

**Issue by tekumara** [astral-sh/ruff-vscode#127]
When starting vscode sometimes:

```
Name: Ruff
Module: ruff
Python extension loading
Waiting for interpreter from python extension.
Python extension loaded
Server Command [RUN]: /Users/tekumara/.pyenv/versions/3.9.13/bin/python /Users/tekumara/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-arm64/bundled/tool/server.py
Server Command [DEBUG]: /Users/tekumara/.pyenv/versions/3.9.13/bin/python /Users/tekumara/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-arm64/bundled/tool/_debug_server.py
Server Command [RUN]: /Users/tekumara/code/dt-xade-prefect-utils/.venv/bin/python /Users/tekumara/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-arm64/bundled/tool/server.py
Server Command [DEBUG]: /Users/tekumara/code/dt-xade-prefect-utils/.venv/bin/python /Users/tekumara/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-arm64/bundled/tool/_debug_server.py
[Error - 15:39:07] Server initialization failed.
Error: command 'ruff.applyAutofix' already exists
	at s.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:106489)
	at Object.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:117:29961)
	at Y.register (/Users/tekumara/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-arm64/dist/extension.js:1:162967)
	at Y.initialize (/Users/tekumara/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-arm64/dist/extension.js:1:162539)
	at w.initializeFeatures (/Users/tekumara/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-arm64/dist/extension.js:1:183031)
	at /Users/tekumara/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-arm64/dist/extension.js:1:174528
[Error - 15:39:07] Starting client failed
Error: command 'ruff.applyAutofix' already exists
	at s.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:106489)
	at Object.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:117:29961)
	at Y.register (/Users/tekumara/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-arm64/dist/extension.js:1:162967)
	at Y.initialize (/Users/tekumara/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-arm64/dist/extension.js:1:162539)
	at w.initializeFeatures (/Users/tekumara/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-arm64/dist/extension.js:1:183031)
	at /Users/tekumara/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-arm64/dist/extension.js:1:174528
```

**Comment by lexicalunit** [comment]
Seeing this as well, the extension completely breaks when it happens. It's happening 100% of the time for me.

```log
Name: Ruff
Module: ruff
Python extension loading
Waiting for interpreter from python extension.
Python extension loaded
Server Command [RUN]: /Users/me/project/env/bin/python /Users/me/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-arm64/bundled/tool/server.py
Server Command [DEBUG]: /Users/me/project/env/bin/python /Users/me/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-arm64/bundled/tool/_debug_server.py
Server Command [RUN]: /Users/me/project/env/bin/python /Users/me/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-arm64/bundled/tool/server.py
Server Command [DEBUG]: /Users/me/project/env/bin/python /Users/me/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-arm64/bundled/tool/_debug_server.py
[Error - 1:44:41 PM] Server initialization failed.
Error: command 'ruff.applyAutofix' already exists
    at s.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:106489)
    at Object.command [as registerCommand] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:117:29961)
    at Y.register (/Users/me/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-arm64/dist/webpack:/ruff/node_modules/vscode-languageclient/lib/common/client.js:1708:53)
    at Y.initialize (/Users/me/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-arm64/dist/webpack:/ruff/node_modules/vscode-languageclient/lib/common/client.js:1688:45)
    at w.then [as initializeFeatures] (/Users/me/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-arm64/dist/webpack:/ruff/node_modules/vscode-languageclient/lib/common/client.js:2592:9)
    at /Users/me/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-arm64/dist/webpack:/ruff/node_modules/vscode-languageclient/lib/common/client.js:2261:12
[Error - 1:44:41 PM] Starting client failed
Error: command 'ruff.applyAutofix' already exists
    at s.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:106489)
    at Object.command [as registerCommand] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:117:29961)
    at Y.register (/Users/me/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-arm64/dist/webpack:/ruff/node_modules/vscode-languageclient/lib/common/client.js:1708:53)
    at Y.initialize (/Users/me/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-arm64/dist/webpack:/ruff/node_modules/vscode-languageclient/lib/common/client.js:1688:45)
    at w.then [as initializeFeatures] (/Users/me/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-arm64/dist/webpack:/ruff/node_modules/vscode-languageclient/lib/common/client.js:2592:9)
    at /Users/me/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-arm64/dist/webpack:/ruff/node_modules/vscode-languageclient/lib/common/client.js:2261:12
Interpreter executable (/Users/me/project/env/bin/ruff) not found; falling back to bundled executable: /Users/me/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-arm64/bundled/libs/bin/ruff
Running Ruff with: ['/Users/me/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-arm64/bundled/libs/bin/ruff', '--no-cache', '--no-fix', '--quiet', '--format', 'json', '-', '--stdin-filename', '/Users/me/project/monolith/service/events/incidents.py']
```

**Comment by charliermarsh** [comment]
I haven't been able to reproduce this and I'm not 100% how to. It's confusing that in both cases, the server seems to be starting twice -- this is what a clean startup looks like:

```
Name: Ruff
Module: ruff
Python extension loading
Waiting for interpreter from python extension.
Python extension loaded
Server Command [RUN]: /usr/local/bin/python /Users/crmarsh/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-arm64/bundled/tool/server.py
Server Command [DEBUG]: /usr/local/bin/python /Users/crmarsh/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-arm64/bundled/tool/_debug_server.py
Using bundled executable: /Users/crmarsh/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-arm64/bundled/libs/bin/ruff
Running Ruff with: ['/Users/crmarsh/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-arm64/bundled/libs/bin/ruff', '--no-cache', '--no-fix', '--quiet', '--format', 'json', '-', '--stdin-filename', '/Users/crmarsh/workspace/ruff/setup.py']
```

**Comment by charliermarsh** [comment]
Is there anything else you can share about your setup? Is it one window? Multiple windows? Is it always on startup?

**Comment by lexicalunit** [comment]
I seem to get it on start up. Just one window. I'm on macOS 13.1, with the latest version of vscode. If I go into my settings and change any `"ruff".[...]` settings, that triggers it again.

If I got into my extensions and disable ruff, then reload vscode, then enable it... it seems to work 🤷🏻‍♀️ 

Another thing that is maybe related is that I also get this error first:
![Screenshot 2023-02-08 at 2 56 02 PM](https://user-images.githubusercontent.com/1903876/217670149-00e1df71-78d9-464e-903e-34a147f89024.png)

Then when I select my virtual env, that's when I get the ruff error... except I just restart vscode for the 10th time, tried this again just to verify I could reproduce it, and this time it worked fine 😅 Now I can't repro it.

**Comment by charliermarsh** [comment]
> Then when I select my virtual env, that's when I get the ruff error... except I just restart vscode for the 10th time, tried this again just to verify I could reproduce it, and this time it worked fine 😅 Now I can't repro it.

Awful, the worst :sob:

**Comment by bcwolven** [comment]
I also get it on startup. Just one window (usually), macOS 12.6.3.

Usually start VSCode from the command line, in working directory, via "code ."

Just tried starting VSCode from the Dock icon instead and it _loaded_ the proper python interpreter and did _not_ throw the same errors. Don't know if that's a hint or just another unreproducible oddity.
¯\\_(ツ)_/¯ 

```Name: Ruff
Module: ruff
Python extension loading
Waiting for interpreter from python extension.
Python extension loaded
Server Command [RUN]: /Users/wolvebc1/Projects/ezie_osse/.ezie_osse_venv/bin/python /Users/wolvebc1/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-x64/bundled/tool/server.py
Server Command [DEBUG]: /Users/wolvebc1/Projects/ezie_osse/.ezie_osse_venv/bin/python /Users/wolvebc1/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-x64/bundled/tool/_debug_server.py
Server Command [RUN]: /Users/wolvebc1/Projects/ezie_osse/.ezie_osse_venv/bin/python /Users/wolvebc1/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-x64/bundled/tool/server.py
Server Command [DEBUG]: /Users/wolvebc1/Projects/ezie_osse/.ezie_osse_venv/bin/python /Users/wolvebc1/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-x64/bundled/tool/_debug_server.py
[Error - 11:40:11 PM] Server initialization failed.
Error: command 'ruff.applyAutofix' already exists
    at s.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:106489)
    at Object.command [as registerCommand] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:117:29961)
    at Y.register (/Users/wolvebc1/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-x64/dist/webpack:/ruff/node_modules/vscode-languageclient/lib/common/client.js:1708:53)
    at Y.initialize (/Users/wolvebc1/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-x64/dist/webpack:/ruff/node_modules/vscode-languageclient/lib/common/client.js:1688:45)
    at w.then [as initializeFeatures] (/Users/wolvebc1/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-x64/dist/webpack:/ruff/node_modules/vscode-languageclient/lib/common/client.js:2592:9)
    at /Users/wolvebc1/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-x64/dist/webpack:/ruff/node_modules/vscode-languageclient/lib/common/client.js:2261:12
[Error - 11:40:11 PM] Starting client failed
Error: command 'ruff.applyAutofix' already exists
    at s.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:106489)
    at Object.command [as registerCommand] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:117:29961)
    at Y.register (/Users/wolvebc1/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-x64/dist/webpack:/ruff/node_modules/vscode-languageclient/lib/common/client.js:1708:53)
    at Y.initialize (/Users/wolvebc1/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-x64/dist/webpack:/ruff/node_modules/vscode-languageclient/lib/common/client.js:1688:45)
    at w.then [as initializeFeatures] (/Users/wolvebc1/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-x64/dist/webpack:/ruff/node_modules/vscode-languageclient/lib/common/client.js:2592:9)
    at /Users/wolvebc1/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-x64/dist/webpack:/ruff/node_modules/vscode-languageclient/lib/common/client.js:2261:12
Using bundled executable: /Users/wolvebc1/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-x64/bundled/libs/bin/ruff
Running Ruff with: ['/Users/wolvebc1/.vscode/extensions/charliermarsh.ruff-2023.6.0-darwin-x64/bundled/libs/bin/ruff', '--no-cache', '--no-fix', '--quiet', '--format', 'json', '-', '--stdin-filename', '/Users/wolvebc1/Projects/ezie_osse/ezieAsPy/test/test_mls.py']
```

**Comment by oliverbeagley-pgg** [comment]
I'm getting the same errors on windows/wsl. Similar to above only happens when running `code .` from a terminal, opening vscode normally doesnt appear to make it happen. Additionally it only seems to happen if I run `code .` from within an activated venv, if I run `deactivate` , `code .` starts up fine and ruff works as intended when the intepreter is selected.

From an active venv it appears to make the automatic select interpreter bit fail, ruff starts erroring/failing once I select the venv python in the selector. Disabling the ruff extension makes the selector work so it seems specific to ruff

**Comment by timendum** [comment]
I'm able to reproduce it, but not every time: I change the "Fix all" checkbox and quickly toggle it a second time, after a new client is started but before the starting is ended (by checking in the Output > Ruff console).

**Comment by charliermarsh** [comment]
What's the "Fix all" checkbox in this context? I'd love to fix this 😅

**Comment by oliverbeagley-pgg** [comment]
Might need others to confirm but it appears to be working fine for me now. Starting vscode from with `code .` within a venv no longer appears to cause the ruff extension (`v2023.8.0`)  and intepreter selection to go haywire for me.

**Comment by johnjtorres** [comment]
I am able to consistently reproduce this issue whenever I create a new virtual environment and open VSCode using the `code .` command.

A workaround, as @timendum suggested, is to open up the Ruff settings in VSCode, toggle `Ruff: Fix All` off, toggle `Ruff: Fix All` on, and then restart VSCode. I don't think the fix is specific to the Fix All setting, because this workaround will work by changing any Ruff settings. For example, I changed the Ruff logging level, restarted VSCode, and the issue was gone.

### Broken scenario
```
Name: Ruff
Module: ruff
Python extension loading
Waiting for interpreter from python extension.
Python extension loaded
Server Command [RUN]: /bin/python3 /home/john/.vscode/extensions/charliermarsh.ruff-2023.12.0-linux-x64/bundled/tool/server.py
Server Command [DEBUG]: /bin/python3 /home/john/.vscode/extensions/charliermarsh.ruff-2023.12.0-linux-x64/bundled/tool/_debug_server.py
Workspace settings: [
    {
        "workspace": "file:///home/john/Code/rufftesting",
        "logLevel": "error",
        "args": [],
        "path": [],
        "interpreter": [
            "/bin/python3"
        ],
        "importStrategy": "fromEnvironment",
        "showNotifications": "off",
        "organizeImports": true,
        "fixAll": true
    }
]
Global settings: {}
Server Command [RUN]: /home/john/Code/rufftesting/venv/bin/python /home/john/.vscode/extensions/charliermarsh.ruff-2023.12.0-linux-x64/bundled/tool/server.py
Server Command [DEBUG]: /home/john/Code/rufftesting/venv/bin/python /home/john/.vscode/extensions/charliermarsh.ruff-2023.12.0-linux-x64/bundled/tool/_debug_server.py
Server shutting down. No more requests!
Server shutting down. No more requests!
Workspace settings: [
    {
        "workspace": "file:///home/john/Code/rufftesting",
        "logLevel": "error",
        "args": [],
        "path": [],
        "interpreter": [
            "/home/john/Code/rufftesting/venv/bin/python"
        ],
        "importStrategy": "fromEnvironment",
        "showNotifications": "off",
        "organizeImports": true,
        "fixAll": true
    }
]
Global settings: {}
[Error - 12:22:58 PM] Server initialization failed.
Error: command 'ruff.applyAutofix' already exists
	at m.registerCommand (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:124270)
	at Object.registerCommand (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:22984)
	at Y.register (/home/john/.vscode/extensions/charliermarsh.ruff-2023.12.0-linux-x64/dist/extension.js:1:163411)
	at Y.initialize (/home/john/.vscode/extensions/charliermarsh.ruff-2023.12.0-linux-x64/dist/extension.js:1:162983)
	at w.initializeFeatures (/home/john/.vscode/extensions/charliermarsh.ruff-2023.12.0-linux-x64/dist/extension.js:1:183475)
	at /home/john/.vscode/extensions/charliermarsh.ruff-2023.12.0-linux-x64/dist/extension.js:1:174972
[Error - 12:22:58 PM] Starting client failed
Error: command 'ruff.applyAutofix' already exists
	at m.registerCommand (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:124270)
	at Object.registerCommand (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:22984)
	at Y.register (/home/john/.vscode/extensions/charliermarsh.ruff-2023.12.0-linux-x64/dist/extension.js:1:163411)
	at Y.initialize (/home/john/.vscode/extensions/charliermarsh.ruff-2023.12.0-linux-x64/dist/extension.js:1:162983)
	at w.initializeFeatures (/home/john/.vscode/extensions/charliermarsh.ruff-2023.12.0-linux-x64/dist/extension.js:1:183475)
	at /home/john/.vscode/extensions/charliermarsh.ruff-2023.12.0-linux-x64/dist/extension.js:1:174972
Interpreter executable (/home/john/Code/rufftesting/venv/bin/ruff) not found; falling back to bundled executable: /home/john/.vscode/extensions/charliermarsh.ruff-2023.12.0-linux-x64/bundled/libs/bin/ruff
Running Ruff with: ['/home/john/.vscode/extensions/charliermarsh.ruff-2023.12.0-linux-x64/bundled/libs/bin/ruff', '--force-exclude', '--no-cache', '--no-fix', '--quiet', '--format', 'json', '-', '--stdin-filename', '/home/john/Code/rufftesting/test.py']

```

### After implementing workaround

```
Name: Ruff
Module: ruff
Python extension loading
Waiting for interpreter from python extension.
Python extension loaded
Server Command [RUN]: /home/john/Code/rufftesting/venv/bin/python /home/john/.vscode/extensions/charliermarsh.ruff-2023.12.0-linux-x64/bundled/tool/server.py
Server Command [DEBUG]: /home/john/Code/rufftesting/venv/bin/python /home/john/.vscode/extensions/charliermarsh.ruff-2023.12.0-linux-x64/bundled/tool/_debug_server.py
Workspace settings: [
    {
        "workspace": "file:///home/john/Code/rufftesting",
        "logLevel": "error",
        "args": [],
        "path": [],
        "interpreter": [
            "/home/john/Code/rufftesting/venv/bin/python"
        ],
        "importStrategy": "fromEnvironment",
        "showNotifications": "off",
        "organizeImports": true,
        "fixAll": true
    }
]
Global settings: {}
Interpreter executable (/home/john/Code/rufftesting/venv/bin/ruff) not found; falling back to bundled executable: /home/john/.vscode/extensions/charliermarsh.ruff-2023.12.0-linux-x64/bundled/libs/bin/ruff
Running Ruff with: ['/home/john/.vscode/extensions/charliermarsh.ruff-2023.12.0-linux-x64/bundled/libs/bin/ruff', '--force-exclude', '--no-cache', '--no-fix', '--quiet', '--format', 'json', '-', '--stdin-filename', '/home/john/Code/rufftesting/test.py']
```

**Comment by charliermarsh** [comment]
Iiinteresting, thank you!

**Comment by fedorenchik** [comment]
The workaround didn't work for me, I tried to reset all settings and restart vs code multiple times. @charliermarsh @johnjtorres

**Comment by konstin** [comment]
I found that is is easy to reproduce when just spamming "Ruff: Restart Server". 

pylance seems to have the same problem with also no solution: https://github.com/microsoft/pylance-release/issues/2765

**Comment by charliermarsh** [comment]
I'm no longer able to reproduce this by spamming restart server, so I'm gonna close and we'll re-open if we hit this again.
