### ISSUE TITLE
Error while updating: "Please restart VS Code before reinstalling Pylance"

### ISSUE THREAD

**Issue by timovp** [astral-sh/ruff-vscode#197]
Hi,

Almost every time ruff updates I get in a loop of error messages that make the update fail. 
I work in WSL1 in VS Code. Updating in 'local installed' works usually fine. But when I update in my WSL 'remote' : "WSL: Ubuntu-20.04" get the following output after the message that the update failed: 

```2023-05-25 14:17:24.304 [error] Error while installing 'charliermarsh.ruff' extension in the remote server. unable to get local issuer certificate
2023-05-25 14:17:24.304 [info] Downloading the 'charliermarsh.ruff' extension locally and install
2023-05-25 14:17:26.366 [info] Downloading the workspace dependencies and packed extensions of 'charliermarsh.ruff' locally and install
2023-05-25 14:17:27.682 [info] Downloaded extension: ms-python.python /C:/Users/xxxxxxxx/AppData/Roaming/Code/CachedExtensionVSIXs/ms-python.python-2023.8.0
2023-05-25 14:17:35.648 [info] Successfully installed 'ms-python.python' extension
2023-05-25 14:17:36.909 [info] Downloaded extension: ms-python.vscode-pylance /C:/Users/xxxxxxxx/AppData/Roaming/Code/CachedExtensionVSIXs/ms-python.vscode-pylance-2023.5.40
2023-05-25 14:17:38.944 [error] Error: Please restart VS Code before reinstalling Pylance.
    at ne.y (/home/xxxxxxxx/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/server/node/server.main.js:153:22296)
    at async ne.h (/home/xxxxxxxx/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/server/node/server.main.js:153:19043)
    at async ne.h (/home/xxxxxxxx/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/server/node/server.main.js:153:21678)
2023-05-25 14:17:38.945 [error] Please restart VS Code before reinstalling Pylance.: Error: Please restart VS Code before reinstalling Pylance.
    at ne.y (/home/xxxxxxxx/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/server/node/server.main.js:153:22296)
    at async ne.h (/home/xxxxxxxx/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/server/node/server.main.js:153:19043)
    at async ne.h (/home/xxxxxxxx/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/server/node/server.main.js:153:21678)
```

Things to note here are that I'm working from behind a proxy and ridiculous firewall / system monitoring, so this often causes the local issues certificate issues.

Sometimes it finally does work, after many times opening and closing VS Code and/or restarting Windows and/or the WSL-service.

Please let me know if you need any other relevant information here.

**Comment by timovp** [comment]
Hmm adding the much loathed
```{
    "http.proxyStrictSSL": false,
}```
to my remote (wsl) settings file seems to solve it. Maybe it was a proxy / ca certificate issue after all. Will report back if next time there is an update it does happen again.
