### ISSUE TITLE
Faulted to apply Ruff formatting to the document

### ISSUE THREAD

**Issue by berceanu** [astral-sh/ruff-vscode#300]
<img width="1212" alt="Screenshot 2023-10-16 at 17 30 30" src="https://github.com/astral-sh/ruff-vscode/assets/4405658/d83cd320-d37d-4890-81ff-539a412f069f">

**Comment by zanieb** [comment]
Hi!

Can you please attach the contents of the file for us to test with?

**Comment by berceanu** [comment]
System info:
```
Visual Studio Code
Version: 1.83.1
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:57:32.750Z (5 days ago)
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.83.1 Chrome/114.0.5735.289 Electron/25.8.4 Safari/537.36
```
Ruff v2023.40.0

**Comment by berceanu** [comment]
> Hi!
> 
> Can you please attach the contents of the file for us to test with?

I tried various files in that repo, for instance:

https://github.com/berceanu/prepic/blob/2f1afe1931069da02494e662955b5c4ac785fd47/prepic/simulation.py#L1

**Comment by berceanu** [comment]
Perhaps the unicode symbols bother `ruff`?

**Comment by zanieb** [comment]
Hm `ruff format` works fine for me with `ruff 0.0.292`. Can you upgrade Ruff and see if it's resolved? `pip install --upgrade ruff`

**Comment by berceanu** [comment]
Doesn't the vscode extension ship with a version of ruff? 

```
The extension ships with ruff==0.0.292.
```

**Comment by berceanu** [comment]
Well, I don't have a locally installed version on my system. How do I open the logs?

**Comment by zanieb** [comment]
The VSCode terminal has output logs for extensions
<img width="1227" alt="Screenshot 2023-10-16 at 10 16 09" src="https://github.com/astral-sh/ruff-vscode/assets/2586601/aae61380-0760-46c2-9430-f50fc0af00b8">

**Comment by berceanu** [comment]
```
2023-10-16 18:23:57.905 [info] [Trace - 18:23:57] Received response 'workspace/executeCommand - (32)' in 5ms. Request failed: KeyError: 'ruff.applyFormat' (-32602).
2023-10-16 18:23:58.877 [info] [Trace - 18:23:58] Sending request 'textDocument/hover - (33)'.
2023-10-16 18:23:58.880 [info] [Trace - 18:23:58] Received response 'textDocument/hover - (33)' in 2ms.
2023-10-16 18:23:59.295 [info] [Trace - 18:23:59] Sending request 'textDocument/hover - (34)'.
2023-10-16 18:23:59.300 [info] [Trace - 18:23:59] Received response 'textDocument/hover - (34)' in 5ms.
2023-10-16 18:24:33.572 [info] [Trace - 18:24:33] Sending request 'textDocument/codeAction - (35)'.
2023-10-16 18:24:33.578 [info] [Trace - 18:24:33] Received response 'textDocument/codeAction - (35)' in 6ms.
2023-10-16 18:24:36.499 [info] [Trace - 18:24:36] Sending request 'workspace/executeCommand - (36)'.
2023-10-16 18:24:36.501 [info] 2023-10-16 18:24:36,500 ERROR Failed to handle request 36 workspace/executeCommand ExecuteCommandParams(command='ruff.applyFormat', arguments=[{'uri': 'file:///Users/berceanu/Development/prepic/prepic/simulation.py', 'version': 1}], work_done_token=None)
Traceback (most recent call last):
  File "/Users/berceanu/.vscode/extensions/charliermarsh.ruff-2023.40.0-darwin-arm64/bundled/libs/pygls/protocol.py", line 338, in _handle_request
    handler(params, msg_id)
  File "/Users/berceanu/.vscode/extensions/charliermarsh.ruff-2023.40.0-darwin-arm64/bundled/libs/pygls/protocol.py", line 83, in decorator
    ret_val = base_func(self, *args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/berceanu/.vscode/extensions/charliermarsh.ruff-2023.40.0-darwin-arm64/bundled/libs/pygls/protocol.py", line 800, in lsp_workspace__execute_command
    cmd_handler = self.fm.commands[params.command]
                  ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'ruff.applyFormat'

2023-10-16 18:24:36.502 [info] [Trace - 18:24:36] Received response 'workspace/executeCommand - (36)' in 3ms. Request failed: KeyError: 'ruff.applyFormat' (-32602).
```

**Comment by charliermarsh** [comment]
Do you have `ruff.enableExperimentalFormatter` set in your `settings.json`?

**Comment by berceanu** [comment]
Nope, I only have:

```
    "extensions.experimental.affinity": {
        "asvetliakov.vscode-neovim": 1
    }
```

**Comment by charliermarsh** [comment]
The formatter is in alpha -- you need to opt into it for now: https://github.com/astral-sh/ruff/blob/main/crates/ruff_python_formatter/README.md#vs-code. Though I'll fix this specific error in the next release to avoid confusion.

**Comment by berceanu** [comment]
Thanks, I confirm that setting

```
    "[python]": {
        "editor.defaultFormatter": "charliermarsh.ruff",
        "editor.formatOnSave": true,
    }
```

fixed my issue.
