### ISSUE TITLE
Better notification when used Ruff not compatible to extension.

### ISSUE THREAD

**Issue by T-256** [astral-sh/ruff-vscode#476]
Notifications on using Ruff v0.3.0 with `ruff.nativeServer` settings enabled:

![image](https://github.com/astral-sh/ruff-vscode/assets/132141463/bc1e5f21-9ce5-44b0-9278-48f7e2a000d4)

### Output
```log
2024-05-23 13:26:39.572 [info] Server: Stop requested
2024-05-23 13:26:39.585 [info] Server run command: c:\Users\User\Desktop\test\.venv\Scripts\python.exe c:\Users\User\.vscode\extensions\charliermarsh.ruff-2024.22.0-win32-x64\bundled\tool\ruff_server.py server --preview
2024-05-23 13:26:39.585 [info] Server: Start requested.
2024-05-23 13:26:39.591 [info] 2024-05-23 13:26:39,580 INFO Shutting down the server
2024-05-23 13:26:39,580 INFO Closing the event loop.

2024-05-23 13:26:39.759 [info] Traceback (most recent call last):
  File "c:\Users\User\.vscode\extensions\charliermarsh.ruff-2024.22.0-win32-x64\bundled\tool\ruff_server.py", line 90, in <module>
    check_compatibility(ruff, RUFF_VERSION_REQUIREMENT)
  File "c:\Users\User\.vscode\extensions\charliermarsh.ruff-2024.22.0-win32-x64\bundled\tool\ruff_server.py", line 55, in check_compatibility
    raise RuntimeError(message)
RuntimeError: Ruff >=0.3.5 required, but found 0.3.0 at C:\Users\User\.rye\shims\ruff.EXE

2024-05-23 13:26:39.767 [info] [Error - 1:26:39 PM] Server initialization failed.
2024-05-23 13:26:39.767 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2024-05-23 13:26:39.767 [info] [Info  - 1:26:39 PM] Connection to server got closed. Server will restart.
2024-05-23 13:26:39.767 [info] true
2024-05-23 13:26:39.768 [info] [Error - 1:26:39 PM] Ruff client: couldn't create connection to server.
2024-05-23 13:26:39.768 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2024-05-23 13:26:39.914 [info] Traceback (most recent call last):
  File "c:\Users\User\.vscode\extensions\charliermarsh.ruff-2024.22.0-win32-x64\bundled\tool\ruff_server.py", line 90, in <module>
    check_compatibility(ruff, RUFF_VERSION_REQUIREMENT)
  File "c:\Users\User\.vscode\extensions\charliermarsh.ruff-2024.22.0-win32-x64\bundled\tool\ruff_server.py", line 55, in check_compatibility
    raise RuntimeError(message)
RuntimeError: Ruff >=0.3.5 required, but found 0.3.0 at C:\Users\User\.rye\shims\ruff.EXE

2024-05-23 13:26:39.923 [info] [Error - 1:26:39 PM] Server initialization failed.
2024-05-23 13:26:39.923 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2024-05-23 13:26:39.923 [info] [Info  - 1:26:39 PM] Connection to server got closed. Server will restart.
2024-05-23 13:26:39.923 [info] true
2024-05-23 13:26:39.923 [info] [Error - 1:26:39 PM] Ruff client: couldn't create connection to server.
2024-05-23 13:26:39.924 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2024-05-23 13:26:39.924 [error] Server: Start failed: Error: Pending response rejected since connection got disposed
2024-05-23 13:26:40.061 [info] Traceback (most recent call last):
  File "c:\Users\User\.vscode\extensions\charliermarsh.ruff-2024.22.0-win32-x64\bundled\tool\ruff_server.py", line 90, in <module>
    check_compatibility(ruff, RUFF_VERSION_REQUIREMENT)
  File "c:\Users\User\.vscode\extensions\charliermarsh.ruff-2024.22.0-win32-x64\bundled\tool\ruff_server.py", line 55, in check_compatibility
    raise RuntimeError(message)
RuntimeError: Ruff >=0.3.5 required, but found 0.3.0 at C:\Users\User\.rye\shims\ruff.EXE

2024-05-23 13:26:40.069 [info] [Error - 1:26:40 PM] Server initialization failed.
2024-05-23 13:26:40.069 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2024-05-23 13:26:40.069 [info] [Info  - 1:26:40 PM] Connection to server got closed. Server will restart.
2024-05-23 13:26:40.069 [info] true
2024-05-23 13:26:40.069 [info] [Error - 1:26:40 PM] Ruff client: couldn't create connection to server.
2024-05-23 13:26:40.069 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2024-05-23 13:26:40.069 [info] [Error - 1:26:40 PM] Restarting server failed
2024-05-23 13:26:40.069 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2024-05-23 13:26:40.212 [info] Traceback (most recent call last):
  File "c:\Users\User\.vscode\extensions\charliermarsh.ruff-2024.22.0-win32-x64\bundled\tool\ruff_server.py", line 90, in <module>
    check_compatibility(ruff, RUFF_VERSION_REQUIREMENT)
  File "c:\Users\User\.vscode\extensions\charliermarsh.ruff-2024.22.0-win32-x64\bundled\tool\ruff_server.py", line 55, in check_compatibility
    raise RuntimeError(message)
RuntimeError: Ruff >=0.3.5 required, but found 0.3.0 at C:\Users\User\.rye\shims\ruff.EXE

2024-05-23 13:26:40.220 [info] [Error - 1:26:40 PM] Server initialization failed.
2024-05-23 13:26:40.220 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2024-05-23 13:26:40.220 [info] [Info  - 1:26:40 PM] Connection to server got closed. Server will restart.
2024-05-23 13:26:40.220 [info] true
2024-05-23 13:26:40.220 [info] [Error - 1:26:40 PM] Ruff client: couldn't create connection to server.
2024-05-23 13:26:40.220 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2024-05-23 13:26:40.221 [info] [Error - 1:26:40 PM] Restarting server failed
2024-05-23 13:26:40.221 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2024-05-23 13:26:40.360 [info] Traceback (most recent call last):
  File "c:\Users\User\.vscode\extensions\charliermarsh.ruff-2024.22.0-win32-x64\bundled\tool\ruff_server.py", line 90, in <module>
    check_compatibility(ruff, RUFF_VERSION_REQUIREMENT)
  File "c:\Users\User\.vscode\extensions\charliermarsh.ruff-2024.22.0-win32-x64\bundled\tool\ruff_server.py", line 55, in check_compatibility
    raise RuntimeError(message)
RuntimeError: Ruff >=0.3.5 required, but found 0.3.0 at C:\Users\User\.rye\shims\ruff.EXE

2024-05-23 13:26:40.368 [info] [Error - 1:26:40 PM] Server initialization failed.
2024-05-23 13:26:40.368 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2024-05-23 13:26:40.368 [info] [Error - 1:26:40 PM] The Ruff server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
2024-05-23 13:26:40.368 [info] [Error - 1:26:40 PM] Ruff client: couldn't create connection to server.
2024-05-23 13:26:40.368 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2024-05-23 13:26:40.369 [info] [Error - 1:26:40 PM] Restarting server failed
2024-05-23 13:26:40.369 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
```

**Comment by dhruvmanila** [comment]
Thank you for the feedback! I agree and in general we should look at the messages sent to the UI to improve the user experience.
