### ISSUE TITLE
The Ruff language server exited with a panic

### ISSUE THREAD

**Issue by matrs** [astral-sh/ruff-vscode#514]
I've been using the ruff server the last days without problems, and suddenly this message appeared in `vscode`:
`The Ruff language server exited with a panic. See the logs for more details.` I wasn't aware of doing any different action when it happened, just  editing code  (notebooks and scripts).

I'm with ruff 0.5.0` ,  `vscode 1.90.2` and extension `ruff-2024.30`
```
2024-07-02 16:06:46.430 [info] Server: Start requested.
2024-07-02 16:07:23.830 [info] Name: Ruff
2024-07-02 16:07:23.830 [info] Module: ruff
2024-07-02 16:07:23.830 [info] Python extension loading
2024-07-02 16:07:23.830 [info] Waiting for interpreter from python extension.
2024-07-02 16:07:23.830 [info] Python extension loaded
2024-07-02 16:07:23.830 [info] Server run command: ~/.vscode/extensions/charliermarsh.ruff-2024.30.0-linux-x64/bundled/tool/ruff_server.py server --preview
2024-07-02 16:07:23.830 [info] Server: Start requested.
2024-07-03 12:20:55.252 [info] panicked at crates/ruff_source_file/src/line_index.rs:176:13:
index out of bounds: the len is 1 but the index is 2

2024-07-03 12:20:55.253 [info]    0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>

2024-07-03 12:22:55.296 [info] panicked at crates/ruff_source_file/src/line_index.rs:176:13:
index out of bounds: the len is 1 but the index is 2
   0: <unknown>
   1: <unknown>
   2: <unknown>
   
2024-07-03 12:22:55.297 [info] 3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
```

Then  I tried to restart the server from the command palette, which after the second time it worked:
```
2024-07-03 12:31:16.160 [info] Server: Stop requested
2024-07-03 12:31:16.178 [info] Server run command: /home/mibu/miniconda3/envs/scrapped/bin/python /home/mibu/.vscode/extensions/charliermarsh.ruff-2024.30.0-linux-x64/bundled/tool/ruff_server.py server --preview
2024-07-03 12:31:16.180 [info] Server: Start requested.
2024-07-03 12:31:16.211 [info] panicked at /home/conda/feedstock_root/build_artifacts/ruff_1719517977307/_build_env/.cargo/registry/src/index.crates.io-6f17d22bba15001f/jod-thread-0.1.2/src/lib.rs:21:21:
called `Result::unwrap()` on an `Err` value: Any { .. }
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>

panicked at /home/conda/feedstock_root/build_artifacts/ruff_1719517977307/_build_env/.cargo/registry/src/index.crates.io-6f17d22bba15001f/jod-thread-0.1.2/src/lib.rs:33:22:
called `Result::unwrap()` on an `Err` value: Any { .. }
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: __libc_start_main
  18: <unknown>


2024-07-03 12:31:47.637 [info] Server: Stop requested
2024-07-03 12:31:47.657 [info] Server run command: /home/mibu/miniconda3/envs/scrapped/bin/python /home/mibu/.vscode/extensions/charliermarsh.ruff-2024.30.0-linux-x64/bundled/tool/ruff_server.py server --preview
2024-07-03 12:31:47.658 [info] Server: Start requested.
```

**Comment by dhruvmanila** [comment]
That's unfortunate. Are you able to reproduce this reliably? If so, will you be able to share the source code on which this panic occurs? Is it occurring in Python file or Jupyter Notebook or either? I suspect it might be occurring in the `offset_to_source_location` function (https://github.com/astral-sh/ruff/blob/e6e09ea93a382d86e4dac5e86a030729184c2de8/crates/ruff_server/src/edit/range.rs#L174-L179) although not sure.

**Comment by matrs** [comment]
i cannot reproduce it consistently, but sometimes, when i copy (`c`) and paste a cell (`v` ) with a ruff warning it it, this happens immediately . What is  consistent, it that when  I copy a cell that have a  ruff warning in it (e.g: line too long), this warning isn't  present in the copied cell.  From a fresh start of the server, this copied cell does have the same warning as the source cell, but it never has it if i don't restart the notebook/the ruff server.

**Comment by matrs** [comment]
So, i think this may be reproducible. If ones copies this  text  into a new cell in a new notebook,  then copy that cell (copy the whole cell with c, not only copy the text),  the new pasted cell won't have the ruff warning in it, and once one hover over that line (or maybe other lines of the copied cell), the server crushes.
```py
qidxs = [9926, 8184, 12563, 6998]
for brand, stores_vcomps_d in all_brand_stores_vcomps.items():
    for store, vcomps_dict in stores_vcomps_d.items():
        for qidx, vcomps in vcomps_dict.items():
            if qidx in qidxs:
                print(f"{brand=}, {store=}, {qidx=}")
                plot_vcomps_dict(vcomps_dict, qidx, embs_all, w_h=(2, 3)) # long line so ruff complains
```

**Comment by dhruvmanila** [comment]
Ok, I think I found the root cause. It's definitely a bug. Thank you for raising this issue!
