### ISSUE TITLE
Ruff Langauge Server crash

### ISSUE THREAD

**Issue by david-waterworth** [astral-sh/ruff-vscode#573]
Sorry I cannot create code snippet for this, but I noticed these messages in my log. I think they occurred when I was dragging a vscode notebooks cell from one position to another (i.e. if I started with cells #1,#2 and #3 then I'm grabbing #2 with my mouse and moving it after #3)

I'm running `ruff==0.5.6` with ruff extension version `v2024.36.0` in vscode 1.92.0 on ubuntu 22.04

```
024-08-07 16:20:18.190 [info] panicked at crates/ruff_source_file/src/line_index.rs:176:13:
index out of bounds: the len is 1 but the index is 16

2024-08-07 16:20:18.245 [info]    0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: start_thread
             at ./nptl/pthread_create.c:442:8
  15: __GI___clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

**Comment by dhruvmanila** [comment]
Interesting, the reproduction steps seems similar to https://github.com/astral-sh/ruff/pull/12575 but here it's a panic instead. I think it's going to be a bit difficult to reproduce this without a code snippet.

It's most likely occurring in this function (https://github.com/astral-sh/ruff/blob/1a8fd7fb91e110a1e559f7f028b710986df10666/crates/ruff_server/src/edit/range.rs#L174-L207).

**Comment by dhruvmanila** [comment]
Does all the three cells contain Python code? Are there any cells that were markdown instead?

**Comment by david-waterworth** [comment]
Yeah there were markdown and python cells, I think the one I was dragging was Python.

**Comment by dhruvmanila** [comment]
I'm playing around with a mix of markdown / code cells and moving them around randomly but I don't see crash :(

**Comment by dhruvmanila** [comment]
Huh, this did give me the following (unrelated) panic though:

```
2024-08-07 15:37:33.967 [info] panicked at crates/ruff_server/src/server/api/requests/format.rs:67:10:
format should only be called on text documents or notebook cells

2024-08-07 15:37:33.975 [info]    0: std::backtrace::Backtrace::force_capture
   1: ruff_server::server::Server::run
   2: std::panicking::rust_panic_with_hook
   3: <std::panicking::begin_panic_handler::StaticStrPayload as core::panic::PanicPayload>::take_box
   4: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   5: _rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::option::expect_failed
   8: <ruff_server::server::api::requests::format::Format as ruff_server::server::api::traits::BackgroundDocumentRequestHandler>::run_with_snapshot
   9: ruff_server::session::Session::take_snapshot
  10: ruff_python_trivia::pragmas::is_pragma_comment
  11: <ruff_server::server::api::requests::hover::Hover as ruff_server::server::api::traits::BackgroundDocumentRequestHandler>::run_with_snapshot
  12: <ruff_server::server::api::requests::hover::Hover as ruff_server::server::api::traits::BackgroundDocumentRequestHandler>::run_with_snapshot
  13: std::sys::pal::unix::thread::Thread::new
  14: __pthread_joiner_wake
```

And, then the editor hangs at "Saving 'issue.ipynb'"

**Comment by david-waterworth** [comment]
Haven't managed to repeat it today, but instead I got this (which I cannot replicate at this stage either)

```
2024-08-08 08:42:03.415 [info] panicked at crates/ruff_server/src/server/api/requests/hover.rs:36:10:
hover should only be called on text documents or notebook cells

2024-08-08 08:42:03.470 [info]    0: ruff_server::server::Server::run::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::option::expect_failed
   7: <ruff_server::server::api::requests::hover::Hover as ruff_server::server::api::traits::
2024-08-08 08:42:03.470 [info] BackgroundDocumentRequestHandler>::run_with_snapshot
   8: core::ops::function::FnOnce::call_once{{vtable.shim}}
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
  10: std::sys_common::backtrace::__rust_begin_short_backtrace
  11: core::ops::function::FnOnce::call_once{{vtable.shim}}
  12: std::sys::pal::unix::thread::Thread::new::thread_start
  13: start_thread
             at ./nptl/pthread_create.c:442:8
  14: __GI___clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

**Comment by dhruvmanila** [comment]
Yeah, I got that as well which I'm tracking it in https://github.com/astral-sh/ruff-vscode/issues/575

**Comment by jbhanks** [comment]
I keep getting similar crashes when using Code on EndeavorOS (Wayland and Nvidia proprietary drivers). I'm not sure exactly what I am doing to trigger it. The most recent occurrence (trace below) happened when I had my back turned to the computer, not actively doing anything.


```
2024-12-31 01:40:26.247 [info] Name: Ruff
2024-12-31 01:40:26.247 [info] Module: ruff
2024-12-31 01:40:26.247 [info] Python extension loading
2024-12-31 01:40:26.247 [info] Waiting for interpreter from python extension.
2024-12-31 01:40:26.247 [info] Python extension loaded
2024-12-31 01:40:26.247 [info] Using interpreter: /bin/python
2024-12-31 01:40:26.247 [info] Falling back to bundled executable: /home/james/.vscode-oss/extensions/charliermarsh.ruff-2024.56.0-linux-x64/bundled/libs/bin/ruff
2024-12-31 01:40:26.278 [info] Resolved 'ruff.nativeServer: auto' to use the native server
2024-12-31 01:40:26.282 [info] Found Ruff 0.8.0 at /home/james/.vscode-oss/extensions/charliermarsh.ruff-2024.56.0-linux-x64/bundled/libs/bin/ruff
2024-12-31 01:40:26.282 [info] Server run command: /home/james/.vscode-oss/extensions/charliermarsh.ruff-2024.56.0-linux-x64/bundled/libs/bin/ruff server
2024-12-31 01:40:26.282 [info] Server: Start requested.
2025-01-01 02:03:40.104 [info] panicked at crates/ruff_source_file/src/line_index.rs:176:13:
index out of bounds: the len is 1 but the index is 24

2025-01-01 02:03:40.107 [info]    0: 
2025-01-01 02:03:40.108 [info] ruff_server::server::Server::run::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::panicking::panic_bounds_check
   7: ruff_source_file::line_index::LineIndex::line_range
   8: <ruff_server::server::api::requests::hover::Hover as ruff_server::server::api::traits::BackgroundDocumentRequestHandler>::run_with_snapshot
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
  10: core::ops::function::FnOnce::call_once{{vtable.shim}}
  11: std::sys::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::pal::unix::thread::Thread::new::thread_start
  14: <unknown>
  15: <unknown>


2025-01-01 02:04:35.872 [info] panicked at crates/ruff_source_file/src/line_index.rs:176:13:
index out of bounds: the len is 1 but the index is 32
   0: ruff_server::server::Server::run::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
2025-01-01 02:04:35.872 [info] 
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::panicking::panic_bounds_check
   7: ruff_source_file::line_index::LineIndex::line_range
   8: <ruff_server::server::api::requests::hover::Hover as ruff_server::server::api::traits::BackgroundDocumentRequestHandler>::run_with_snapshot
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
  10: core::ops::function::FnOnce::call_once{{vtable.shim}}
  11: std::sys::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::pal::unix::thread::Thread::new::thread_start
  14: <unknown>
  15: <unknown>


2025-01-01 02:04:36.505 [info] panicked at crates/ruff_source_file/src/line_index.rs:176:13:
index out of bounds: the len is 1 but the index is 20

2025-01-01 02:04:36.506 [info]    0: ruff_server::server::Server::run::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::panicking::panic_bounds_check
   7: ruff_source_file::line_index::LineIndex::line_range
   8: <ruff_server::server::api::requests::hover::Hover
2025-01-01 02:04:36.506 [info]  as ruff_server::server::api::traits::BackgroundDocumentRequestHandler>::run_with_snapshot
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
  10: core::ops::function::FnOnce::call_once{{vtable.shim}}
  11: std::sys::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::
2025-01-01 02:04:36.506 [info] call_once{{vtable.shim}}
  13: std::sys::pal::unix::thread::Thread::new::thread_start
  14: <unknown>
  15: <unknown>


2025-01-01 02:09:55.310 [info] panicked at crates/ruff_source_file/src/line_index.rs:176:13:
index out of bounds: the len is 1 but the index is 30
   0: ruff_server::server::Server::run::{{closure}}
   1: 
2025-01-01 02:09:55.310 [info] std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::panicking::panic_bounds_check
   7: ruff_source_file::line_index::LineIndex::line_range
   8: <ruff_server::server::api::requests::hover::Hover as ruff_server::server::api::traits::BackgroundDocumentRequestHandler>::run_with_snapshot
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
  10: core::ops::function::FnOnce::call_once{{vtable.shim}}
  11: std::sys::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{
2025-01-01 02:09:55.310 [info] {vtable.shim}}
  13: std::sys::pal::unix::thread::Thread::new::thread_start
  14: <unknown>
  15: <unknown>


2025-01-01 02:09:55.906 [info] panicked at crates/ruff_source_file/src/line_index.rs:176:13:
index out of bounds: the len is 1 but the index is 27
   0: ruff_server::server::Server::run::{{closure}}
   1: std::panicking
2025-01-01 02:09:55.906 [info] ::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::panicking::panic_bounds_check
   7: ruff_source_file::line_index::LineIndex::line_range
2025-01-01 02:09:55.906 [info] 
   8: <ruff_server::server::api::requests::hover::Hover as ruff_server::server::api::traits::BackgroundDocumentRequestHandler>::run_with_snapshot
   9: core::ops::function::
2025-01-01 02:09:55.906 [info] FnOnce::call_once{{vtable.shim}}
  10: core::ops::function::FnOnce::call_once{{vtable.shim}}
  11: std::sys::backtrace
2025-01-01 02:09:55.906 [info] ::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::pal::unix::thread::Thread::new::
2025-01-01 02:09:55.906 [info] thread_start
  14: <unknown>
  15: <unknown>


2025-01-01 02:09:57.501 [info] panicked at crates/ruff_source_file/src/line_index.rs:176:13:
index out of bounds: the len is 1 but the index is 29
   0: ruff_server::server::Server::run::{{closure
2025-01-01 02:09:57.502 [info] }}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::panicking::panic_bounds_check
   7: ruff_source_file::line_index::LineIndex::line_range
   8: <ruff_server::server::api::requests::hover::Hover as ruff_server::server::api::traits::BackgroundDocumentRequestHandler>::run_with_snapshot
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
  
2025-01-01 02:09:57.502 [info] 10: core::ops::function::FnOnce::call_once{{vtable.shim}}
  11: std::sys::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::pal::unix::
2025-01-01 02:09:57.502 [info] thread::Thread::new::thread_start
  14: <unknown>
  15: <unknown>


2025-01-01 02:10:41.464 [info] panicked at crates/ruff_source_file/src/line_index.rs:176:13:
index out of bounds: the len is 1 but the index is 16
   0: ruff_server::server::Server::run::{{closure}}
  
2025-01-01 02:10:41.464 [info]  1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::panicking::panic_bounds_check
   7: ruff_source_file::line_index::LineIndex::line_range
   8: <ruff_server::server::api::requests::hover::Hover as ruff_server::server::api::traits::BackgroundDocumentRequestHandler>::run_with_snapshot
   9: core::ops::
2025-01-01 02:10:41.464 [info] function::FnOnce::call_once{{vtable.shim}}
  10: core::ops::function::FnOnce::call_once{{vtable.shim}}
  11: std::sys::backtrace::__rust_begin_short_backtrace
  12
2025-01-01 02:10:41.464 [info] : core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::pal::unix::thread::Thread::new::thread_start
  14: <unknown>
  15: <unknown>


2025-01-01 02:11:11.616 [info] panicked at crates/ruff_source_file/src/line_index.rs:176:13:
index out of bounds: the len is 1 but the index is 30
   0: 
2025-01-01 02:11:11.616 [info] ruff_server::server::Server::run::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::panicking::panic_bounds_check
   7: ruff_source_file::line_index::LineIndex::line_range
   8: <ruff_server::server::api::requests::hover
2025-01-01 02:11:11.616 [info] ::Hover as ruff_server::server::api::traits::BackgroundDocumentRequestHandler>::run_with_snapshot
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
  10: core::ops::function::FnOnce::call_once{{vtable.shim}}
  11: std::sys::backtrace
2025-01-01 02:11:11.616 [info] ::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::pal::unix::thread::Thread::new::thread_start
  14: <unknown>
  15: <unknown>


2025-01-01 02:11:13.075 [info] panicked at crates/ruff_source_file/src/line_index.rs:176:13:
index out of bounds: the len is 1 but the index is 30
   0: ruff_server::server::Server::run::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace
2025-01-01 02:11:13.075 [info] ::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::panicking::panic_bounds_check
   7: ruff_source_file::line_index::LineIndex::line_range
   8: <lsp_types::Range as ruff_server::edit::range::RangeExt>::to_text_range
   9: ruff_server::edit::text_document::TextDocument::apply_changes
  10: ruff_server::edit::notebook::NotebookDocument::update
  11: ruff_server::session::index::Index::update_notebook_document
  12: <ruff_server::server::api::notifications
2025-01-01 02:11:13.075 [info] ::did_change_notebook::DidChangeNotebook as ruff_server::server::api::traits::SyncNotificationHandler>::run
  13: core::ops::function::FnOnce::call_once{{vtable.shim}}
  14: std::sys::backtrace
2025-01-01 02:11:13.075 [info] ::__rust_begin_short_backtrace
  15: core::ops::function::FnOnce::call_once{{vtable.shim}}
  16: std::sys::pal::unix::thread::Thread::new::
2025-01-01 02:11:13.075 [info] thread_start
  17: <unknown>
  18: <unknown>


2025-01-01 02:11:13.078 [info] panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/jod-thread-0.1.2/src/lib.rs:33:22:
called `Result::unwrap()` on an `Err` value: Any { .. }

2025-01-01 02:11:13.078 [info]    0: ruff_server::server::Server::run::{{closure}
2025-01-01 02:11:13.078 [info] }
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3
2025-01-01 02:11:13.078 [info] : std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt

2025-01-01 02:11:13.078 [info]    6: core::result::unwrap_failed
   7: ruff_server::server::Server::run
 
2025-01-01 02:11:13.079 [info]   8: ruff::run
   9: ruff::main
  10: std::sys::
2025-01-01 02:11:13.079 [info] backtrace::__rust_begin_short_backtrace
  11: std::rt::lang_start::{{closure}}
  12: std::rt
2025-01-01 02:11:13.079 [info] ::lang_start_internal
  13: main
  14: <unknown>
  15: __libc_start_main
  16: 
2025-01-01 02:11:13.079 [info] <unknown>


2025-01-01 02:11:13.085 [info] [Info  - 2:11:13 AM] Connection to server got closed. Server will restart.
2025-01-01 02:11:13.085 [info] true
2025-01-01 15:23:36.556 [info] panicked at crates/ruff_server/src/server/api/requests/hover.rs:36:10:
hover should only be called on text documents or notebook cells

2025-01-01 15:23:36.559 [info]    0: ruff_server::server::Server::run::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}

2025-01-01 15:23:36.559 [info]    3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::option::expect_failed
   7: <ruff_server::server::api::requests::hover::Hover as ruff_server::server::api::traits::BackgroundDocumentRequestHandler>::run_with_snapshot
   8: core::
2025-01-01 15:23:36.559 [info] ops::function::FnOnce::call_once{{vtable.shim}}
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
  10: std::sys::backtrace::__rust_begin_short_backtrace
2025-01-01 15:23:36.559 [info] 
  11: core::ops::function::FnOnce::call_once{{vtable.shim}}
  12: std::sys::pal::unix::thread::Thread::new::thread_start
2025-01-01 15:23:36.559 [info] 
  13: <unknown>
  14: <unknown>


2025-01-01 15:27:40.353 [info] panicked at crates/ruff_server/src/server/api/requests/hover.rs:36:10:
hover should only be called on text documents or notebook cells
   0: 
2025-01-01 15:27:40.353 [info] ruff_server::server::Server::run::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::option::expect_failed
   7: <ruff_server::server::api::requests::hover::Hover as ruff_server::server::api::traits::BackgroundDocumentRequestHandler>::run_with_snapshot
   8: core::ops::function::FnOnce::call_once{{vtable.shim}}
   9: core
2025-01-01 15:27:40.353 [info] ::ops::function::FnOnce::call_once{{vtable.shim}}
  10: std::sys::backtrace::__rust_begin_short_backtrace
  11: core::ops::function::FnOnce::call_once{{vtable.shim}}
  12: std::sys::pal::unix::thread::Thread::new::thread_start
  13: <unknown>
  14: <unknown>


2025-01-01 15:27:42.808 [info] panicked at crates/ruff_server/src/server/api/requests/hover.rs:36:10:
hover should only be called on text documents or notebook cells
 
2025-01-01 15:27:42.808 [info]   0: ruff_server::server::Server::run::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core
2025-01-01 15:27:42.808 [info] ::panicking::panic_fmt
   6: core::option::expect_failed
   7: <ruff_server::server::api::requests::hover::Hover as ruff_server::server::api
2025-01-01 15:27:42.808 [info] ::traits::BackgroundDocumentRequestHandler>::run_with_snapshot
   8: core::ops::function::FnOnce::call_once{{vtable.shim}}

2025-01-01 15:27:42.808 [info]    9: core::ops::function::FnOnce::call_once{{vtable.shim}}
  10: std::sys
2025-01-01 15:27:42.808 [info] ::backtrace::__rust_begin_short_backtrace
  11: core::ops::function::FnOnce::call_once{{vtable.shim}}
  
2025-01-01 15:27:42.808 [info] 12: std::sys::pal::unix::thread::Thread::new::thread_start
  13: <unknown>
  14: 
2025-01-01 15:27:42.808 [info] <unknown>


2025-01-01 15:27:43.930 [info] panicked at crates/ruff_server/src/server/api/requests/hover.rs:36:10:
hover should only be called on text documents or notebook cells
   0: ruff_server::server::Server::run::{{closure}
2025-01-01 15:27:43.930 [info] }
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6
2025-01-01 15:27:43.930 [info] : core::option::expect_failed
   7: <ruff_server::server::api::requests::hover::Hover as ruff_server::server::api::traits::BackgroundDocumentRequestHandler
2025-01-01 15:27:43.930 [info] >::run_with_snapshot
   8: core::ops::function::FnOnce::call_once{{vtable.shim}}
   9: core::
2025-01-01 15:27:43.930 [info] ops::function::FnOnce::call_once{{vtable.shim}}
  10: std::sys::backtrace::__rust_begin_short_backtrace
  11: core
2025-01-01 15:27:43.930 [info] ::ops::function::FnOnce::call_once{{vtable.shim}}
  12: std::sys::pal::unix::thread::Thread::new
2025-01-01 15:27:43.930 [info] ::thread_start
  13: <unknown>
  14: <unknown>


2025-01-01 15:27:44.624 [info] panicked at crates/ruff_server/src/server/api/requests/hover.rs:36:10:
hover should only be called on text documents or notebook cells

2025-01-01 15:27:44.624 [info]    0: ruff_server::server::Server::run::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::option::expect_failed
   7: <ruff_server::server::api::requests::hover::
2025-01-01 15:27:44.624 [info] Hover as ruff_server::server::api::traits::BackgroundDocumentRequestHandler>::run_with_snapshot
   8: core::ops::function::FnOnce::call_once{{vtable.shim}}
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
  10: std::sys::backtrace::__rust_begin_short_backtrace
  11: core::ops::function::FnOnce::call_once{{
2025-01-01 15:27:44.624 [info] vtable.shim}}
  12: std::sys::pal::unix::thread::Thread::new::thread_start
  13: <unknown>
  14: <unknown>


2025-01-01 16:39:31.481 [info] panicked at crates/ruff_source_file/src/line_index.rs:176:13:
index out of bounds: the len is 1 but the index is 2

2025-01-01 16:39:31.481 [info]    0: ruff_server::server::Server::run::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::panicking::panic_bounds_check
   7: 
2025-01-01 16:39:31.481 [info] ruff_source_file::line_index::LineIndex::line_range
   8: <ruff_server::server::api::requests::hover::Hover as ruff_server::server::api::traits::BackgroundDocumentRequestHandler>::run_with_snapshot
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
  10: core::ops::function::FnOnce::call_once{{vtable.shim}}

2025-01-01 16:39:31.481 [info]   11: std::sys::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::pal::unix::thread::Thread::new::thread_start
  14: <unknown>
  
2025-01-01 16:39:31.481 [info] 15: <unknown>


2025-01-01 16:39:31.685 [info] panicked at crates/ruff_source_file/src/line_index.rs:176:13:
index out of bounds: the len is 1 but the index is 2

2025-01-01 16:39:31.685 [info]    0: ruff_server::server::Server::run::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}
2025-01-01 16:39:31.685 [info] }
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6
2025-01-01 16:39:31.685 [info] : core::panicking::panic_bounds_check
   7: ruff_source_file::line_index::LineIndex::line_range
   8: <ruff_server::server::api::requests
2025-01-01 16:39:31.685 [info] ::hover::Hover as ruff_server::server::api::traits::BackgroundDocumentRequestHandler>::run_with_snapshot
   9: core::ops::function::FnOnce
2025-01-01 16:39:31.685 [info] ::call_once{{vtable.shim}}
  10: core::ops::function::FnOnce::call_once{{vtable.shim}}
 
2025-01-01 16:39:31.685 [info]  11: std::sys::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}
2025-01-01 16:39:31.685 [info] }
  13: std::sys::pal::unix::thread::Thread::new::thread_start
  14: <unknown>

2025-01-01 16:39:31.685 [info]   15: <unknown>


2025-01-01 16:51:32.776 [info] panicked at crates/ruff_server/src/server/api/requests/hover.rs:36:10:
hover should only be called on text documents or notebook cells

2025-01-01 16:51:32.776 [info]    0: ruff_server::server::Server::run::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
2025-01-01 16:51:32.776 [info] 
   6: core::option::expect_failed
   7: <ruff_server::server::api::requests::hover::Hover as ruff_server::server::api::traits::BackgroundDocumentRequestHandler>::run_with_snapshot
2025-01-01 16:51:32.776 [info] 
   8: core::ops::function::FnOnce::call_once{{vtable.shim}}
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
2025-01-01 16:51:32.776 [info] 
  10: std::sys::backtrace::__rust_begin_short_backtrace
  11: core::ops::function::FnOnce::call_once{{vtable.shim}}

2025-01-01 16:51:32.776 [info]   12: std::sys::pal::unix::thread::Thread::new::thread_start
  13: <unknown>
  14: <unknown>


2025-01-01 16:51:57.915 [info] panicked at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/alloc/src/string.rs:1919:29:
assertion failed: self.is_char_boundary(n)
   0: ruff_server::server::Server::run::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::panicking::panic
   7: alloc::string
2025-01-01 16:51:57.915 [info] ::String::replace_range
   8: ruff_server::edit::text_document::TextDocument::apply_changes
   9: ruff_server::edit::notebook::NotebookDocument::update
  10: ruff_server::session::index::Index::update_notebook_document
  11: <ruff_server::server::api::notifications::did_change_notebook::DidChangeNotebook as ruff_server::server::api::traits::SyncNotificationHandler>::run
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::backtrace::__rust_begin_short_backtrace
  14: core::ops::function::FnOnce::call_once{{vtable.shim}}
  15: std::sys::pal::unix::thread::Thread::new::thread_start
  16: <unknown>
  17: <unknown>


2025-01-01 16:51:57.918 [info] panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/jod-thread-0.1.2/src/lib.rs:33:22:
called `Result::unwrap()` on an `Err` value: Any { .. }

2025-01-01 16:51:57.918 [info]    0: ruff_server::server::Server::run::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
  
2025-01-01 16:51:57.918 [info]  3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: ruff_server::
2025-01-01 16:51:57.918 [info] server::Server::run
   8: ruff::run
   9: ruff::main
  10: std::sys::backtrace::__rust_begin_short_backtrace
  11: std::rt::lang_start::
2025-01-01 16:51:57.919 [info] {{closure}}
  12: std::rt::lang_start_internal
  13: main
  14: <unknown>
  15: __libc_start_main
  16: <unknown>


2025-01-01 16:51:57.923 [info] [Info  - 4:51:57 PM] Connection to server got closed. Server will restart.
2025-01-01 16:51:57.923 [info] true
```

**Comment by dhruvmanila** [comment]
I think this is the same issue as https://github.com/astral-sh/ruff-vscode/issues/644 and should be fixed by https://github.com/astral-sh/ruff/pull/15398.

**Comment by dhruvmanila** [comment]
The fix will be released as part of **Ruff 0.9.1**.

Closing this for now, but feel free to comment if this issue persists even after upgrading to the mentioned Ruff version.
