### ISSUE TITLE
Ruff in VSCode repteadly crashing on hover: The Ruff language server exited with a panic

### ISSUE THREAD

**Issue by aflip** [astral-sh/ruff-vscode#644]
I am working in vscode on a .ipynb notebook, and everytime my cursor hovers over any code, i get the ruff panic message as above

example of the code it crashed over

```py
def search_and_lookup(query_vector, top_k=10):
    # Perform the search
    results = ngt_corpus_index.search(query_vector, top_k)
    
    # Look up the document information for each result
    enriched_results = []    
    for ngt_index, distance in results:
        # Find the corresponding document and chunk
        cumulative_count = 0
        for doc in lookup_table:
            if ngt_index < cumulative_count + doc['num_chunks']:
                chunk_id = ngt_index - cumulative_count
                enriched_results.append({
                    'ngt_index': ngt_index,
                    'distance': distance,
                    'document_id': doc['document_id'],
                    'chunk_id': chunk_id
                })
                break
            cumulative_count += doc['num_chunks']
    
    return enriched_results
```
[settins.json](https://github.com/user-attachments/files/17882103/settins.json)

Ruff.log is here: It's the same message repeated. 

```
2024-11-23 22:45:07.465 [info] Name: Ruff
2024-11-23 22:45:07.465 [info] Module: ruff
2024-11-23 22:45:07.465 [info] Python extension loading
2024-11-23 22:45:07.465 [info] Waiting for interpreter from python extension.
2024-11-23 22:45:07.465 [info] Python extension loaded
2024-11-23 22:45:07.465 [info] Using interpreter: /bin/python
2024-11-23 22:45:07.465 [info] Using bundled executable: /home/XX/.vscode-oss/extensions/charliermarsh.ruff-2024.56.0-linux-x64/bundled/libs/bin/ruff
2024-11-23 22:45:07.465 [info] Found Ruff 0.8.0 at /home/XX/.vscode-oss/extensions/charliermarsh.ruff-2024.56.0-linux-x64/bundled/libs/bin/ruff
2024-11-23 22:45:07.465 [info] Server run command: /home/XX/.vscode-oss/extensions/charliermarsh.ruff-2024.56.0-linux-x64/bundled/libs/bin/ruff server
2024-11-23 22:45:07.465 [info] Server: Start requested.
2024-11-23 23:37:34.744 [info] panicked at crates/ruff_server/src/server/api/requests/hover.rs:36:10:
hover should only be called on text documents or notebook cells

2024-11-23 23:37:34.807 [info]    0: 
2024-11-23 23:37:34.807 [info] ruff_server::server::Server::run::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::option::expect_failed
   7: <ruff_server::server::api::requests::hover::Hover as ruff_server::server::api::traits::BackgroundDocumentRequestHandler>::run_with_snapshot
   8: core::ops::function::FnOnce::call_once{{vtable.shim}}
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
  10: std::sys::backtrace::__rust_begin_short_backtrace
  11: core::ops::function::FnOnce::call_once{{vtable.shim}}
  12: std::sys::pal::unix::thread::Thread::new::thread_start
  13: start_thread
             at ./nptl/pthread_create.c:447:8
  14: clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78


2024-11-23 23:37:35.122 [info] panicked at crates/ruff_server/src/server/api/requests/hover.rs:36:10:
hover should only be called on text documents or notebook cells
   0: ruff_server::server::Server::run::
2024-11-23 23:37:35.122 [info] {{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::option::expect_failed
   7: <ruff_server::server::api::requests::hover::Hover as ruff_server::server::api::traits::BackgroundDocumentRequestHandler>::run_with_snapshot
   8: core::ops::function::FnOnce::call_once{{vtable.shim}}
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
  10: std::sys::backtrace::__rust_begin_short_backtrace
  11: core::ops::function::FnOnce::call_once{{vtable.shim}}
  12: std::sys::pal::unix::thread::Thread::new::thread_start
  13: start_thread
             at ./nptl/pthread_create.c:447:8
  14: clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78


2024-11-23 23:37:35.316 [info] panicked at crates/ruff_server/src/server/api/requests/hover.rs:36:10:
hover should only be called on text documents or notebook cells
   0: ruff_server::server::Server::run::{{closure}}
   1: std::panicking::rust_panic_with_hook
2024-11-23 23:37:35.316 [info] 
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::option::expect_failed
   7: <ruff_server::server::api::requests::hover::Hover as ruff_server::server::api::traits::BackgroundDocumentRequestHandler>::run_with_snapshot
   8: core::ops::function::FnOnce::call_once{{vtable.shim}}
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
  10: std::sys::backtrace::__rust_begin_short_backtrace
  11: core::ops::function::FnOnce::call_once{{vtable.shim}}
  12: std::sys::pal::unix::thread::Thread::new::thread_start
  13: start_thread
             at ./nptl/pthread_create.c:447:8
  14: clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78


2024-11-23 23:37:37.547 [info] panicked at crates/ruff_server/src/server/api/requests/hover.rs:36:10:
hover should only be called on text documents or notebook cells
   0: ruff_server::server::Server::run::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4
2024-11-23 23:37:37.547 [info] : rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::option::expect_failed
   7: <ruff_server::server::api::requests::hover::Hover as ruff_server::server::api::traits::BackgroundDocumentRequestHandler>::run_with_snapshot
   8: core::ops::function::FnOnce::call_once{{vtable.shim}}
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
  10: std::sys::backtrace::__rust_begin_short_backtrace
  11: core::ops::function::FnOnce::call_once{{vtable.shim}}
  12: std::sys::pal::unix::thread::Thread::new::thread_start
  13: start_thread
             at ./nptl/pthread_create.c:447:8
  14: clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78


2024-11-23 23:39:09.761 [info] panicked at crates/ruff_server/src/server/api/requests/hover.rs:36:10:
hover should only be called on text documents or notebook cells

2024-11-23 23:39:09.762 [info]    0: ruff_server::server::Server::run::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::option::expect_failed
   7: <ruff_server::server::api::requests::hover::Hover as ruff_server::server::api::traits::BackgroundDocumentRequestHandler>::run_with_snapshot
   8: core::ops::function::FnOnce::call_once{{vtable.shim}}
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
  10: std::sys::backtrace::__rust_begin_short_backtrace
  11: core::ops::function::FnOnce::call_once{{vtable.shim}}
  12: std::sys::pal::unix::thread::Thread::new::
2024-11-23 23:39:09.762 [info] thread_start
  13: start_thread
             at ./nptl/pthread_create.c:447:8
  14: clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78


2024-11-23 23:39:12.228 [info] panicked at crates/ruff_server/src/server/api/requests/hover.rs:36:10:
hover should only be called on text documents or notebook cells
   0: ruff_server::server::Server::run::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
  
2024-11-23 23:39:12.229 [info]  6: core::option::expect_failed
   7: <ruff_server::server::api::requests::hover::Hover as ruff_server::server::api::traits::BackgroundDocumentRequestHandler>::run_with_snapshot
   8: core::ops::function::FnOnce::call_once{{vtable.shim}}
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
  10: std::sys::backtrace::__rust_begin_short_backtrace
  11: core::ops::function::FnOnce::call_once{{vtable.shim}}
  12: std::sys::pal::unix::thread::Thread::new::thread_start
  13: start_thread
             at ./nptl/pthread_create.c:447:8
  14: clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78


2024-11-23 23:41:15.697 [info] panicked at crates/ruff_server/src/server/api/requests/hover.rs:36:10:
hover should only be called on text documents or notebook cells

2024-11-23 23:41:15.698 [info]    0: ruff_server::server::Server::run::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::option::expect_failed
   7: <ruff_server::server::api::requests::hover::Hover as ruff_server::server::api::traits::BackgroundDocumentRequestHandler>::run_with_snapshot
   8: core::ops::function::FnOnce::call_once{{vtable.shim}}
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
  10: std::sys::backtrace::__rust_begin_short_backtrace
  11: core::ops::function::FnOnce::call_once{{vtable.shim}}
  12: std::sys::pal::unix::thread::Thread::new::thread_start
  13: start_thread
             at ./nptl/pthread_create.c:447:8
  14: clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78


2024-11-23 23:42:34.445 [info] panicked at crates/ruff_server/src/server/api/requests/hover.rs:36:10:
hover should only be called on text documents or notebook cells

2024-11-23 23:42:34.445 [info]    0: ruff_server::server::Server::run::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::option::expect_failed
   7: <ruff_server::server::api::requests::hover::Hover as ruff_server::server::api::traits::BackgroundDocumentRequestHandler>::run_with_snapshot
   8: core::ops::function::FnOnce::call_once{{vtable.shim}}
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
  10: std::sys::backtrace::__rust_begin_short_backtrace
  11: core::ops::function::FnOnce::call_once{{vtable.shim}}
  12: std::sys::pal::unix::thread::Thread::new::thread_start
  13: start_thread
             at ./nptl/pthread_create.c:447:8
  14: clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

2024-11-23 23:41:15.697 [info] panicked at crates/ruff_server/src/server/api/requests/hover.rs:36:10:
hover should only be called on text documents or notebook cells

2024-11-23 23:41:15.698 [info]    0: ruff_server::server::Server::run::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::option::expect_failed
   7: <ruff_server::server::api::requests::hover::Hover as ruff_server::server::api::traits::BackgroundDocumentRequestHandler>::run_with_snapshot
   8: core::ops::function::FnOnce::call_once{{vtable.shim}}
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
  10: std::sys::backtrace::__rust_begin_short_backtrace
  11: core::ops::function::FnOnce::call_once{{vtable.shim}}
  12: std::sys::pal::unix::thread::Thread::new::thread_start
  13: start_thread
             at ./nptl/pthread_create.c:447:8
  14: clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78


```

**Comment by aflip** [comment]
I changed the source of ruff from bundled to environment and now it's not crashing. I don't get it.

**Comment by MichaReiser** [comment]
This sounds similar to https://github.com/astral-sh/ruff-vscode/issues/607

Do you have a notebook that you could share that we can use for reproduction?

**Comment by MichaReiser** [comment]
I just tried creating a notebook with the code above and I can't get Ruff to crash when hovering. Can you tell me a bit more about your setup? What extensions are you using? Can you share a video where you hover over a name and Ruff crashes. I wonder what I do wrong that I'm unable to reproduce.

**Comment by aflip** [comment]
I am unable to reproduce the bug myself. it was present all day yesterday, despite various usual interventions like restarting code, the system etc.It stopped when I switched to useenv, but it's still using the bundled ruff. `Found Ruff 0.8.0 at /home/XXX/.vscode-oss/extensions/charliermarsh.ruff-2024.56.0-linux-x64/bundled/libs/bin/ruff`  and i am usually running the notebook from a mamba environment that doesn't have ruff so internally, nothing has changed. this is the notebook i was running  https://github.com/pinecone-io/examples/blob/master/learn/generation/better-rag/02a-alt-chunking-methods.ipynb

**Comment by MichaReiser** [comment]
I don't mind keeping the issue open for a little longer. Maybe you'll be able to reproduce the bug in the coming days. I do think there's a bug in Ruff or VS Code (or in combination with some other extension), but we just have never been able to reproduce it, which makes it hard to fix.

**Comment by dhruvmanila** [comment]
Thanks for the issue.

As per the panic message, it should only occur when a hover request is being made by the client for the entire notebook instead of a single text document (Python file) or a notebook cell. But, the method through which is panics (`DocumentQuery::as_single_document`) could also return `None` if there's a bug in adding the cell index (`NotebookDocument.cell_index` field) or if the `NotebookCell` itself doesn't exists in the vector (`NotebookDocument.cells` field). If we can figure out which one is the actual cause of this issue, that can be very helpful.

I think we can update the return type of `as_single_document` from `Option` to `Result` in which we can capture what the source of the error is.

**Comment by dhruvmanila** [comment]
@aflip Hi, I've added the new message and the latest Ruff release contains it. If possible, can you upgrade your Ruff version to the latest version and provide us the new messages whenever the panic occurs? That would really help in understanding the root cause of this and allow us to fix this quickly.

**Comment by aflip** [comment]
@dhruvmanila have upgraded, so far no more panic. will upload if anything happens. thank you

**Comment by rnckp** [comment]
@dhruvmanila @MichaReiser Unfortunately I observe these crashes too, see the logfile I have mailed you and my identical comment [here](https://github.com/astral-sh/ruff-vscode/issues/607#issuecomment-2568160233). Thanks for any help in this matter.

**Comment by dhruvmanila** [comment]
Thanks for sharing the logs, I'll look at that today.

**Comment by dhruvmanila** [comment]
I looked into this a bit and here are my notes so far:

First panic message on line 133133 for the following notebook:
```
vscode-notebook-cell:/Volumes/1TB%20Home%20SSD/GitHub/_%20statistikZH/sprache-vereinfachen/03_llm_evaluations_250102.ipynb#X55sZmlsZQ%3D%3D
```
when requested hover for the following position:
```
line: 9
character: 38
```
Relevant parts of the notebook URI:
```
Notebook: sprache-vereinfachen/03_llm_evaluations_250102.ipynb
Cell: X55sZmlsZQ%3D%3D
```
Logs are only for this specific notebook, there are no other notebooks. But there are log messages for different cells in the notebook. Let's focus on the above cell first.

The last `didChange` request for that specific cell:

```
2025-01-02 18:56:19.518 [info] [Trace - 18:56:19] Sending notification 'notebookDocument/didChange'.
2025-01-02 18:56:19.518 [info] Params: {
    "notebookDocument": {
        "version": 1806,
        "uri": "file:///Volumes/1TB%20Home%20SSD/GitHub/_%20statistikZH/sprache-vereinfachen/03_llm_evaluations_250102.ipynb"
    },
    "change": {
        "cells": {
            "textContent": [
                {
                    "document": {
                        "uri": "vscode-notebook-cell:/Volumes/1TB%20Home%20SSD/GitHub/_%20statistikZH/sprache-vereinfachen/03_llm_evaluations_250102.ipynb#X55sZmlsZQ%3D%3D",
                        "version": 13
                    },
                    "changes": [
                        {
                            "range": {
                                "start": {
                                    "line": 7,
                                    "character": 0
                                },
                                "end": {
                                    "line": 7,
                                    "character": 0
                                }
                            },
                            "rangeLength": 0,
                            "text": "cols = [\"text\\", \\"model\\"]\\ndfr = dfr[cols]\\ndfr = dfr.set_index(\\"model\\", append=True).unstack()\\ndfr.columns = [\\"claude_35\\", \\"source\\"]\\ncols = [\\"source\\", \\"claude_35\\"]\\ndfr = dfr[cols]\\ndfr.to_excel(f\\"\{DATA_DIR\}eval_results_ES.xlsx\\", index=False)\\n# Annotate the data manually"
                        }
                    ]
                }
            ]
        }
    }
}
```

which adds the following source content on line 7:

```py
cols = ["text", "model"]
dfr = dfr[cols]
dfr = dfr.set_index("model", append=True).unstack()
dfr.columns = ["claude_35", "source"]
cols = ["source", "claude_35"]
dfr = dfr[cols]
dfr.to_excel(f"{DATA_DIR}eval_results_ES.xlsx", index=False)
# Annotate the data manually
```

This would mean that line 9 should be valid and should be part of the code cell unless the `didChange` handler is doing something else.

I tried to mimic this behavior but that didn't reproduce the panic. I think I'll need to move a bit backwards. My intuition is that if there's a bug then it is most likely in `didChange` request handling.

**Comment by Quemoy** [comment]
I would just like to add that I'm starting to notice this quite often, and I think I have the panic  reproducible now.

It happens if I'm editing a Python jupyter notebook (with interactive execution). Let's say I write code in 3 jupyter cells, A B and C, then execute the cells one by one. After, I move say cell B to before where cell A was, Ruff does two things:
1. Red underlines names in cell C which depends on the code in cell B (but shouldn't, because cell B still exists)
2. After a bit, throws the "The Ruff language server exited with a panic"  message.

I hope this is of use to you.

**Comment by dhruvmanila** [comment]
Thank you all for the patience. This issue has been fixed and will be released in **Ruff 0.9.1**.

If you encounter this issue again after upgrading to the mentioned Ruff version, please feel free to comment here or open a new issue for that.
