### ISSUE TITLE
Ruff extension configured as formatter but does not actually format Python files

### ISSUE THREAD

**Issue by rohanbalkondekar** [astral-sh/ruff-vscode#653]
![Image](https://github.com/user-attachments/assets/7fcf0b9f-6ce8-4174-a3a8-e8e03e6de9db)

**Description:**  
I encountered a prompt in VSCode stating:  
> "Extension 'Ruff' is configured as formatter but it cannot format 'Python'-files."

**Additional Context:**

- **VSCode version:**  
  Version: 1.95.3  
  Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813  
  Date: 2024-11-13T14:50:04.152Z  
  Electron: 32.2.1  
  ElectronBuildId: 10427718  
  Chromium: 128.0.6613.186  
  Node.js: 20.18.0  
  V8: 12.8.374.38-electron.0  
  OS: Linux x64 6.8.0-49-generic

- **Ruff extension version:** `ruff 0.6.8`

- **Python version:** `3.10.12`

- **Operating system:** Ubuntu Mate  
  Distributor ID: Ubuntu  
  Description: Ubuntu 22.04.5 LTS  
  Release: 22.04  
  Codename: jammy

**Comment by MichaReiser** [comment]
Hi @rohanbalkondekar 

I'm sorry that you're running into this. Would you mind sharing the ruff extension logs with us? 

> If you encounter any issues with the extension or the language server, please refer to the logs in the output panel in VS Code. You can access the logs by running the Ruff: Show logs command.

**Comment by lig** [comment]
I've recreated venv and now it works. Have no idea what that was 🤷‍♂

**Comment by dhruvmanila** [comment]
> How can I get those logs?

You can refer to the [troubleshooting guide](https://github.com/astral-sh/ruff-vscode#troubleshooting) for that.

> I've recreated venv and now it works. Have no idea what that was 🤷‍♂

If possible, can you try removing the venv and see if it still works? It would be useful to know what this issue is about and how to resolve it. Do you have a `ruff` executable available on `PATH` globally (related [`ruff.importStrategy`](https://docs.astral.sh/ruff/editors/settings/#importstrategy)?

**Comment by lig** [comment]
I'll try to debug this on a second laptop.

Yes, I always have ruff installed via `uv tool` or `pipx` and another one in the project's venv.

**Comment by danieleds** [comment]
I'm using a vscode workspace with multiple projects - each project has its own .venv.

I'm not sure if this issue started appearing right after I switched to the vscode workspace project layout, or after that.

However, I noticed that when I tried running the command "Ruff: Restart Server", Ruff complained that it couldn't find the Python executable in the root of my workspace (instead of using the one in the sub-project).

Setting the ruff extension to use the bundled ruff did not help.

What helped was:
 - Created a dummy .venv at the root of my workspace
 - Restarted the ruff server

Is it possible that the ruff extension is not playing well with vscode workspaces?

**Comment by TheFloatingString** [comment]
In my case, following @dhruvmanila 's recommendation, I realized that my VS Code editor was in a virtual environment. By clicking on the venv box in the bottom navbar (right next to the Python name, where the 3.11.4 appears in my screenshot):

![Image](https://github.com/user-attachments/assets/1010ccd9-6510-470f-b45c-89272a7519eb)

I selected the global Python as the Python interpreter to use. Next, I went to extensions and re-configured Ruff, and now Ruff works.

I don't know how Ruff can work for specific virtual environments, though at least reverting to a global Python interpreter and re-configuring Ruff may be a tentative fix.

**Comment by dhruvmanila** [comment]
> I don't know how Ruff can work for specific virtual environments, though at least reverting to a global Python interpreter and re-configuring Ruff may be a tentative fix.

The extension doesn't care whether you're in a virtual environment or not as it has no need / benefit to do so. It might be something else that must be wrong here.

Do you mind checking if the logs can provide anything? Refer to the [troubleshooting guide](https://github.com/astral-sh/ruff-vscode#troubleshooting) for how to do so.

**Comment by davidcjuergens** [comment]
If it helps: I was getting the same `Configure Default Formatter` issue with ruff just now, even though it looked like the correct python interpreter was being sourced in the bottom right of the screen. I just re-selected the same interpreter from the `Select Interpreter` menu, and it seems this issue has gone away for me after I did this.

**Comment by danieleds** [comment]
**Scenario:**
- Multi-root workspace. Each Python workspace has its own `.venv`. Other workspaces are non-python.
- When running the command "Ruff: Restart Server", you get an error indicating that the extension cannot find the ruff executable, or cannot find/parse the `.venv` folder from a path that has nothing to do with the correct one.
- Configuring the ruff extension to use the bundled version of ruff does not work.


**Solution:**
I finally solved by adding the following to my `.code-workspace`:

```
"settings": {
    "ruff.interpreter": [
      "${workspaceFolder}/.venv/bin/python"
    ]
}
```

**Comment by YassineElbouchaibi** [comment]
https://github.com/astral-sh/ruff-vscode/issues/653#issuecomment-2684697931 This solved it for me too

**Comment by stevenh** [comment]
I had this today after working it was working for months, I was trying to debug, setting the log `"ruff.trace.server": "messages"` when I got an electron error pop up which killed and reloaded everything after which it was just working again.

Before that I'd tried setting the python interpreter and the environment, nothing seemed to work.

I did notice that using restart server it never seemed to complete as doing that again resulting it a message about the restart being queued.

**Comment by stevenh** [comment]
I was in the process of debugging the issues with restart hanging that I mentioned above, had found the issue was `api.environments.resolveEnvironment` never rejecting or fulfilling the promise due to an issue in Python Environments extension where it would throw:
```log
rejected promise not handled within 1 second: TypeError: Cannot read properties of undefined (reading 'executable')
extensionHostProcess.js:176
stack trace: TypeError: Cannot read properties of undefined (reading 'executable')
    at t.refreshPyenv (/Users/steve/.vscode/extensions/ms-python.vscode-python-envs-0.3.11421010-darwin-arm64/dist/extension.js:2:531591)
    at /Users/steve/.vscode/extensions/ms-python.vscode-python-envs-0.3.11421010-darwin-arm64/dist/extension.js:2:522903
```

When it was fixed by an update for the Python Extension released: 2025-05-23, 11:46:50 version: 0.3.11431010

Glad its fixed upstream but if not I have a patch which fixes in this extension.

Hope if fixes this issue for some folks too.

**Comment by gmanny** [comment]
This should have been obvious to me, but I still managed to spend too much time before realizing this, so want to mention it for the benefit of others:

**Make sure you update you VS Code** if you didn't launch it in a long time

**Comment by rsxdalv** [comment]
> I was in the process of debugging the issues with restart hanging that I mentioned above, had found the issue was `api.environments.resolveEnvironment` never rejecting or fulfilling the promise due to an issue in Python Environments extension where it would throw:
> 
> ```
> rejected promise not handled within 1 second: TypeError: Cannot read properties of undefined (reading 'executable')
> extensionHostProcess.js:176
> stack trace: TypeError: Cannot read properties of undefined (reading 'executable')
>     at t.refreshPyenv (/Users/steve/.vscode/extensions/ms-python.vscode-python-envs-0.3.11421010-darwin-arm64/dist/extension.js:2:531591)
>     at /Users/steve/.vscode/extensions/ms-python.vscode-python-envs-0.3.11421010-darwin-arm64/dist/extension.js:2:522903
> ```
> 
> When it was fixed by an update for the Python Extension released: 2025-05-23, 11:46:50 version: 0.3.11431010
> 
> Glad its fixed upstream but if not I have a patch which fixes in this extension.
> 
> Hope if fixes this issue for some folks too.

Ah, Python Environments Extension, yep, yep yep.
